### ISSUE TITLE
Input and output clarification 

### ISSUE THREAD

**Issue by justkrismanohar** [bob-carpenter/java-arithcode#1]
First of all thanks for this implementation, great job!

I am a little be confused about how to use this lib with raw binary data. For example if I have the binary bits 1001 should I create a text file with that bit stream as the input to the encoder or pact the bit stream into a byte and then write that byte to the disk? 

If I create a text file with the text 1001, the actual binary on the disk would be 
0000 0001 0000 0000 0000 0000 0000 0001. 

My confusion is what will the encoder see 1001 or 000...001

Thanks

**Comment by bob-carpenter** [comment]
It'll take raw binary as is.  You certainly don't want to write
it out as characters (though in theory, that's the same info and
should compress just fine, in real life there's smoothing and
limited memory).  

There are some binary example files.  
- Bob

**Comment by justkrismanohar** [comment]
Oh...thanks! That explains alot. I took the same information, and fed it to the encoder both ways firstly as  a text file with the characters 1 and 0, and secondly by packing the bits into chars and writing those out to a file. In both cases the size of the output file was identical - that was very confusing!  Thanks for clearing that up!
